name: GENERATE APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 修正后的稀疏检出配置
          sparse-checkout: |
            *
            !.gitattributes
            sparse-checkout-cone-mode: false  # 关键参数
          show-progress: false  # 避免冗长输出

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'gradle'
          cache-dependency-path: '**/build.gradle'  # 精确缓存控制

      - name: Fix execution permissions
        timeout-minutes: 2
        run: |
          # 分步权限修复
          echo "Current gradlew permissions: $(stat -c '%A %a %n' gradlew)"
          find . -type f -name 'gradlew' -exec chmod +x {} \;
          find . -type f -name '*.sh' -exec chmod +x {} \;
          echo "Updated permissions: $(stat -c '%A %a %n' gradlew)"

      - name: Build With Gradle
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx4g
        run: |
          ./gradlew clean --stacktrace
          ./gradlew assembleRelease \
            --parallel \
            --no-configuration-cache \
            --warning-mode=fail

      - name: Prepare App
        run: |
          APK_SOURCE="${{ github.workspace }}/app/build/outputs/apk/release"
          echo "APK源目录结构:"
          ls -lhR $APK_SOURCE || true  # 失败时仍显示结构
          
          mkdir -p "${{ github.workspace }}/apk"
          rsync -av --progress "$APK_SOURCE/" "${{ github.workspace }}/apk/" \
            --include='*.apk' --exclude='*'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk_${{ github.run_number }}_${{ github.sha_short }}
          path: ${{ github.workspace }}/apk/*.apk
          retention-days: 3
          compression-level: 9
