name: GENERATE APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 确保检出保留文件权限
          sparse-checkout: |
            /*
            !.gitattributes
          persist-credentials: false

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'gradle'
          check-latest: true

      # 关键修复：显式设置文件权限
      - name: Fix execution permissions
        run: |
          # 修复gradlew权限
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            echo "✅ gradlew permissions updated"
          else
            echo "❌ gradlew not found"
            exit 1
          fi
          
          # 修复其他可能丢失权限的文件
          find . -name '*.sh' -exec chmod +x {} \;

      - name: Build With Gradle
        timeout-minutes: 15
        run: |
          # 带诊断信息的清理
          ./gradlew clean --stacktrace || (echo "##[error]Clean failed"; exit 1)
          
          # 带资源监控的构建
          ./gradlew assembleRelease \
            --build-cache \
            --parallel \
            --no-daemon \
            --warning-mode all \
            -Dorg.gradle.java.home="$JAVA_HOME" \
            -Dorg.gradle.vfs.watch=true \
            -PciBuild=true

      - name: Prepare App
        run: |
          APK_SOURCE="$GITHUB_WORKSPACE/app/build/outputs/apk/release"
          
          # 带时间戳的日志
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] APK源目录: $APK_SOURCE"
          
          if [ ! -d "$APK_SOURCE" ]; then
            echo "##[error]APK directory missing at $APK_SOURCE"
            ls -R $GITHUB_WORKSPACE/app/build/outputs || true
            exit 1
          fi

          mkdir -p "$GITHUB_WORKSPACE/apk"
          find "$APK_SOURCE" -name '*.apk' -exec cp -v {} "$GITHUB_WORKSPACE/apk/" \;

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: box-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.sha }}
          path: ${{ github.workspace }}/apk/*.apk
          retention-days: 7
          if-no-files-found: error
